- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_distribution != 'Ubuntu'

- name: Include variables for Ubuntu
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

- include_tasks: "install-{{ ansible_os_family }}.yml"
