Vagrant.configure(2) do |config|

  # CentOS 6
  config.vm.define "centos6" do |centos6|
    centos6.vm.box = "geerlingguy/centos6"
    centos6.vm.hostname = "java-centos6"
  end

  # CentOS 7
  config.vm.define "centos7" do |centos7|
    centos7.vm.box = "geerlingguy/centos7"
    centos7.vm.hostname = "java-centos7"
  end

  # Ubuntu 14.04
  config.vm.define "ub14" do |ub14|
    ub14.vm.box = "geerlingguy/ubuntu1404"
    ub14.vm.hostname = "java-ub14"
  end

  # Ubuntu 16.04
  config.vm.define "ub16" do |ub16|
    ub16.vm.box = "geerlingguy/ubuntu1604"
    ub16.vm.hostname = "java-ub16"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
