- name: Test Java role
  hosts: all
  become: yes

  tasks:
    - debug:
        msg: >-
          Testing with Ansible {{ ansible_version.full }} using Python {{ ansible_facts.python_version }}
          on {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}

    - import_role:
        name: java

- name: Validate Java role
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure Java was installed
      command: java -version
      changed_when: no
      register: java_test_result

    - debug:
        var: java_test_result.stderr_lines
